100-hours-a-week/22-tenten-be

- src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
- src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
- src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostImage.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostImageRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
- src/main/java/com/kakaobase/snsapp/global/common/s3/controller/S3Controller.java
- src/main/java/com/kakaobase/snsapp/global/common/s3/exception/S3ErrorCode.java
- src/main/java/com/kakaobase/snsapp/global/common/s3/exception/S3Exception.java
- src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
Close #13 Post Post 도메인 엔티티, 레포지토리 완성
- Post도메인에 필요한 Entity, Repository구현
- 이미지 업로드시 버킷내에 유저 프로필/게시글로 나누는 디렉토리 구조를
게시글은 게시판 종류별로 디렉토리 위치에 업로드 하도록 변경
- Post Entity 생성
- PostImage Entity 생성
- PostRepository 생성
- PostImageRepository생성
- Member Entity의 @Table에 인덱싱 정보 추가
- S3Exception가 매개변수 타입을 S3ErrorCode로 받는걸 BaseErrorCode타입으로 받도록 변경
현재 Entity에 @Where로 작성되어있는 걸 나중에 @Fileter로 변경해야함
> [FEAT] Post 도메인 엔티티, 레포지토리 완성

- build.gradle
- src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
- src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetails.java
- src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
- src/main/java/com/kakaobase/snsapp/domain/members/repository/MemberRepository.java
- src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
- src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
- src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostLike.java
- src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostErrorCode.java
- src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostException.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostLikeService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
- src/main/java/com/kakaobase/snsapp/global/common/s3/controller/S3Controller.java
- src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
- src/main/java/com/kakaobase/snsapp/global/error/handler/GlobalExceptionHandler.java
- src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
- src/main/java/com/kakaobase/snsapp/global/security/SecurityUtil.java
- src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
- src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
- src/main/resources/application.yml
Close #15
- 게시글 CRUD및 기능 구현
- 게시글 목록 조회 기능 구현
- 게시글 상세 조회 기능 구현
- 게시글 좋아요 기능 구현
- Post관련 요청, 응답 Dto구현
- Dto기반 Converter구현
- 게시글 생성, 삭제, 목록 조회, 상세조회 Controller 구현
- 게시글 좋아요, 좋아요 취소 Controller 구현
- Controller에 맞는 비지니스 로직 구현
- MariaDB기반의 설정을 MySQL8.0으로 변경
- Authentication 객체에서 id값을 null로 받아오는 에러를 수정
- 아직 구현되지 않은 follows관련 서비스 로직은 전부 제거하거나 주석처리
게시글 목록 조회시 Cursor + Created_at을 사용해 조회하는 것을
우선은 Cursor를 기반으로 조회하도록 변경
이 부분은 차후 성능, 최적화 시 한번 더 논의해야함
Authentication 객체의 경우 일관적으로 Optional로 반환하게 로직을 수정하고,
중복되는 메서드를 제거하는 것으로 일시적으로 에러 해결.
그러나 아직 왜 String으로 반환해야 하는 로직이 필요한 지 의문점이 있음.
Spring Security의 호환성 상 Stirng이 좋다는데, 이는 차후 고도화때 조사해볼 예정
> [FEAT] 게시글 CRUD구현

- src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetails.java
- src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetailsService.java
- src/main/java/com/kakaobase/snsapp/domain/auth/service/UserAuthenticationService.java
- src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
- src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/converter/LikeConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/CommentLike.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/Recomment.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/RecommentLike.java
- src/main/java/com/kakaobase/snsapp/domain/comments/exception/CommentErrorCode.java
- src/main/java/com/kakaobase/snsapp/domain/comments/exception/CommentException.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
Close #22
- CustomUserDetails의 생성자 매개변수를 직렬화 가능한 값만 받도록 변경
- 비즈니스 로직을 제외한 Comment도메인에 필요한 요소 구현
Comment도메인의 Dto, Converter, Exception, Entity, Repository, Controller생성
- CustomUserDetails 생성자 매개변수 변경
CustomUserDetails가 member객체를 매개변수를 받는 로직에서
직렬화 가능한 매개변수 email, password, id, role, isEnable만 받도록 수정
- 용도에 따른 CustomUserDetails생성자 분리
CustomUserDetails는 로그인시 사용되는 email, password를 포함한 나머지 필드를 받는 생성자와
JWT를 포함한 요청시 구현되는 id, role, isEnable만 받는 생성자 2개가 존재
- UserAuthenticationService의 login로직을 변경
> [BE-FEAT] Comment-Domain구현

- src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
- src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
- src/main/java/com/kakaobase/snsapp/domain/comments/exception/CommentErrorCode.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentLikeService.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
Close #24
- 댓글에 관한 비즈니스 로직 구현
댓글 생성, 삭제 메서드 추가
댓글 목록조회 메서드 추가
댓글 상세 조회 메서드 추가
댓글 좋아요 등록 메서드 추가
댓글 좋아요 취소 메서드 추가
대댓글 좋아요 등록 메서드 추가
대댓글 좋아요 취소 메서드 추가
통합형 댓글로 자기참조형으로 대댓글을 구현하던걸
분리형 Entity로 변경
Pase 객체로 반환하던 목록값을
List형을 반환하도록 수정
현재 댓글 삭제시 관련된 대댓글이 전부 삭제되는데,
이를 에타처럼 (알수 없음)으로 표기하고 대댓글을 살려둘지,
아니면 전부 삭제할지 논의 필요
> [BE - FEAT] Comment도메인 서비스 로직 구현

- build.gradle
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
- src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/YouTubeSummaryService.java
- src/main/java/com/kakaobase/snsapp/global/config/WebClientConfig.java
- src/main/resources/application.yml
Close #26
- PostDomain에 youtube요약 기능 추가
- PostController에 youtube요약 api추가
- Post 요청, 응답dto에 youtube api관련 record추가
- PostService에 유튜브 요약 내용을 Entity에 저장하는 기능 추가 
- YouTubeSummaryService로 Ai서버에 유투브 요약 요청을 보내고, 값을 받아오는 로직 구현
- WebClientConfig를 통해, Ai서버와 통신시 필요한 설정값 구현
- yml파일에 Ai서버 url추가
원래 비동기로 구현할 예정이었으나, 비동기 구현시
call-back url이 필요하며 백엔드와 ai간 api명세가 대거 바뀔거거 같아
동기로 구현
> [BE - FEAT] 유튜브 요약 기능 추가

- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
- src/main/java/com/kakaobase/snsapp/domain/posts/dto/BotRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
- src/main/java/com/kakaobase/snsapp/domain/posts/event/PostCounter.java
- src/main/java/com/kakaobase/snsapp/domain/posts/event/PostCreatedEvent.java
- src/main/java/com/kakaobase/snsapp/domain/posts/event/PostEventListener.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
- src/main/java/com/kakaobase/snsapp/global/common/constant/BotConstants.java
- src/main/java/com/kakaobase/snsapp/global/config/AsyncConfig.java
Close #28
- 게시글이 5개 생성될 때마다 AI 서버와 통신하여 자동으로 봇 게시글을 생성하는 기능 구현
- 이벤트 기반 아키텍처를 사용하여 게시글 생성과 봇 로직을 분리
- `BotRequestDto`: AI 서버와의 통신을 위한 요청/응답 DTO
- `CreatePostRequest`: AI 서버에 전송할 게시글 생성 요청
- `AiPostResponse`: AI 서버로부터의 응답
- `BotPostService`: AI 봇 게시글 생성 비즈니스 로직
- 최근 5개 게시글 조회 및 AI 서버 요청 처리
- WebClient를 사용한 비동기 통신
- `PostCreatedEvent`: 게시글 생성 이벤트
- ApplicationEvent를 상속하여 Spring 이벤트 시스템과 통합
- `PostEventListener`: 게시글 생성 이벤트 처리
- `@Async`를 통한 비동기 처리로 메인 플로우에 영향 없음
- `PostCounter`: 게시판별 게시글 카운터 관리
- Thread-safe한 구현 (ConcurrentHashMap, AtomicInteger)
- `BotConstants`: 봇 관련 상수 정의
- 봇 ID(1213L), 닉네임, 기수 등 중앙 관리
- `AsyncConfig`: 비동기 처리 설정
- ThreadPoolTaskExecutor 커스텀 설정
- `PostService`: 게시글 생성 시 이벤트 발행 기능 추가
- `ApplicationEventPublisher`를 사용하여 `PostCreatedEvent` 발행
- `Post`, `PostConverter` : 엔티티가 …
> [BE - FEAT] 소셜봇 구현

- src/main/java/com/kakaobase/snsapp/domain/comments/converter/BotRecommentConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/BotRecommentRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/event/CommentCreatedEvent.java
- src/main/java/com/kakaobase/snsapp/domain/comments/event/CommentEventListener.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/BotRecommentService.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
Close #30
- AI 소셜봇이 게시글에 달린 댓글에 자동으로 대댓글을 작성하는 기능을 추가했습니다.
- 봇 게시글에 일반 사용자가 댓글을 작성하면, 이벤트 기반으로 AI 서버와 통신하여 자연스러운 대댓글을 생성합니다.
- `CommentCreatedEvent`: 댓글 생성 이벤트 클래스 구현 (댓글 ID, 게시글 ID, 작성자 정보 포함)
- `CommentEventListener`: 이벤트 리스너 구현 (봇 게시글 여부 확인 후 봇 대댓글 서비스 호출)
- `BotRecommentService`: AI 서버와 통신하여 봇 대댓글을 생성하는 핵심 서비스
- AI 서버 호출 (WebClient 사용, 타임아웃 및 재시도 로직 포함)
- 응답 검증 및 대댓글 저장
- 에러 처리 및 로깅
- `BotRecommentRequestDto`: AI 서버 요청/응답용 DTO (게시글 정보, 댓글 정보, 대댓글 정보 포함)
- `BotRecommentConverter`: 엔티티-DTO 간 변환 로직 구현
- `BotConstants`: 봇 관련 상수 정의 (봇 ID, 닉네임, 기수, 타임아웃 설정 등)
- `ApplicationEventPublisher` 주입 추가
- `createComment()` 메서드에서 `CommentCreatedEvent` 발행
- 게시글 작성자 ID 조회하여 이벤트에 포함
- `getMemberBotInfo()` 메서드 추가 (닉네임, 기수 정보만 조회) 
- 대댓글 조회 시 페이징 크기를 100개로 설정하여 대부분의 케이스 커버
- className 정보는 임시로 하드코딩 처리 (추후 …
> [BE - FEAT] 소셜봇 대댓글 기능 구현

- src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
- src/main/java/com/kakaobase/snsapp/domain/auth/dto/AuthResponseDto.java
Close #32
- 로그인시 회원의 기수명과 닉네임을 반환하도록 수정
- AuthResponseDto: 기존의 TokenResponse로 되어있는 응답dto를 TokenResponse, LoginResponse로 분리
- AuthController: 로그인 메서드가 LoginResponse를 반환하도록 수정
> [FIX] 로그인이 회원의 닉네임 기수를 반환하도록 수정

- src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
- src/main/java/com/kakaobase/snsapp/domain/auth/converter/AuthConverter.java
- src/main/java/com/kakaobase/snsapp/domain/auth/entity/RevokedRefreshToken.java
- src/main/java/com/kakaobase/snsapp/domain/auth/service/UserAuthenticationService.java
- src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
- src/main/resources/application.yml
Close #
- 로그아웃 시 refresh token이 서버로 전송되지 않는 문제 수정
- 쿠키의 path 설정 문제로 인해 브라우저에서 쿠키가 필터링되어 전송되지 않았음
- 로그아웃 API 호출 시 refresh token 쿠키를 정상적으로 추출하여 토큰 무효화 처리가 가능하도록 수정
```diff
cookie:
- refresh-token-path: /auth/tokens/refresh
+ refresh-token-path: /auth
```
```diff
cookie:
+ secure: false  # 개발 환경에서는 HTTP 사용을 위해 false로 설정
```
- 기존 Controller에서 처리하던 토큰 무효화 로직을 Service 레이어로 이동
- refresh token을 revoked_refresh_tokens 테이블로 이동하는 기능 구현
- RevokedRefreshToken 엔티티 및 Repository 추가
- 기존 쿠키 Path: `/auth/tokens/refresh`
- 로그아웃 API 경로: `/auth/tokens`
- 쿠키의 Path가 `/auth/tokens/refresh`로 제한되어 있어서, `/auth/tokens` 경로로의 요청에서는 해당 쿠키가 전송되지 않음
- refresh token 무효화 시 revoked_refresh_tokens 테이블로 이동하여 재사용 방지
- 개발 환경과 운영 환경의 쿠키 Secure 설정 분리
- HttpOnly 속성 유지로 XSS 공격 방지
> [BE - FEAT] 로그아웃시 revoked_refresh_tokens토큰값을 갱신하도록 수정 

- src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
className을 class_name으로,
githubUrl을 github_url로 수정
Close #54
- MemberRequestDto에 SignUp요청의 필드 오탈자 수정
className을 class_name으로,
githubUrl을 github_url로 수정
> [FIX] SignUp RequestDto의 오탈자 수정

- src/main/java/com/kakaobase/snsapp/Application.java
- src/main/resources/application.yml
Close #67 
- 댓글, 대댓글 조회시 시간이 UTC에 맞춰져 있는 것을 Timezone.setDefault로 서울 시간으로 고정
- Aplication의 메인 메서드에 Timezone.setDefault을 서울로 설정
- yml파일을 통해 DB에 저장되는 표준시는 UTC로 통일
현재 방식은 임시 방편이며, 다음과 같은 문제를 초래할 수 있기 때문에 꼭 바꿔줘야 합니다
- Spring Batch, Scheduler, Quartz 등의 스케줄러가 Asia/Seoul 기준으로 실행되어 잘못된 시점에 작업 실행 할 수 있음
- 운영 서버, 개발 서버, 테스트 서버, Docker 컨테이너 간 TimeZone 불일치로 인한 데이터 mismatch 및 장애 가능성 존재
- AWS, Azure 등 클라우드 인프라에서 UTC가 표준인데 Asia/Seoul로 변경 시 예상 외 동작 및 버그 유발 가능성 있음
> Fix /#67 fix comment time

- src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
Close #69
- 게시글의 created_at을 JVM시간에 맞춰 반환하도록 변경
PostResponseDto의 createdAt필드에 있는 @JsonFormat제거
> [BE- FIX] PostResponseDto의 createAt에 있는 JsonForamt어노테이션 제거

- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
Close #75 
-  댓글, 대댓글을 작성순으로 조회하도록 변경
- CommentRepository의 조회 메서드를 작성순으로 반환하도록
- RecommentRepository의 조회 메서드를 작성순으로 반환하도록
- RecommentRepository의 조회 메서드 findByCommentIdWithCursor를 findByRecommentIdWithCursor로 변경
> [BE - FIX] 댓글, 대댓글을 작성순으로 반환하도록 수정

- src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
Close #79 
- 소셜봇 게시글 요청시 봇이 작성한 게시글을 필터링 하지 못한 에러를 수정
소셜봇Id와 게시글의 Id 비교를 "=="으로 파악하던걸
.equals로 수정
> [FIX] 소셜봇 게시글 필터 로직을 수정

- build.gradle
- src/main/resources/application-prod.yml
- src/main/resources/console-appender.xml
- src/main/resources/discord-error-appender.xml
- src/main/resources/logback-spring.xml
Close #111 
- 배포 서버의 로그를 디스코드 웹훅으로 전송
discord webhook 의존성 추가
196e87f3dffa40a26c5c131e9634b6ea49afe7a6
webhook url 외부 설정
77a2b3e69549ac6c2a4cea8961d8b0af5c5e9b18
log 설정 및 포맷, 전송 정의
15db99cd08db74085c3d3623320ef16177f2c7bf
> [BE - !HOTFIX] 배포 서버의 로그를 디스코드 웹훅으로 전송

- src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
- src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
- src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
- src/main/resources/application.yml
Close #141 
- API 경로 통일화 및 게시글 접근 권한 관리 기능 구현
- Spring Security 메서드 레벨 보안 활성화를 통한 접근 제어 강화
- **API 경로 통일화**: 모든 API 엔드포인트에 `/api` prefix 추가
- **게시글 접근 권한 관리**: 로그인 사용자만 게시글 목록 및 상세 조회 가능하도록 변경
- **Method Security 활성화**: `@EnableMethodSecurity(prePostEnabled = true)` 추가로 `@PreAuthorize` 동작 가능
- **AccessChecker 정상 동작**: 메서드 레벨 보안 활성화로 커스텀 접근 권한 체크 로직 적용
- **게시글 접근 제한**: 비로그인 사용자의 게시글 접근 차단
- **Converter 에러 추적**: 에러 발생 시 원인 추적이 가능하도록 로깅 개선
- Context path 설정을 통한 API 경로 표준화
- Spring Security 설정 업데이트 (URL 패턴 매칭 수정)
- JwtAuthenticationFilter의 excludedPaths 업데이트
- API 경로 변경으로 인한 프론트엔드 호출 URL 수정 필요성
- 게시글 접근 권한 정책에 대한 추가 논의 (공개 게시판 vs 회원 전용)
- AccessChecker 로직의 확장 가능성 (게시판별 세분화된 권한 관리)
> [BE - FIX] 이메일 인증시 401에러가뜨는 버그 수정

- src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
Close #144 
- Context path 설정(`/api`) 적용 후 JWT 필터에서 제외 경로 패턴 불일치 문제 해결
- API 경로 표준화에 따른 JWT 인증 필터 설정 수정
- **JWT 필터 경로 패턴 수정**: `excludedPaths`에 `/api` prefix 추가하여 context path와 일치시킴
- **인증 제외 경로 정상화**: 회원가입, 이메일 인증, 토큰 발급 등의 경로가 JWT 필터에서 올바르게 제외되도록 수정
```java
// 기존 (context path 미반영)
"/auth/tokens" → "/api/auth/tokens"
"/users/email/verification-requests" → "/api/users/email/verification-requests"
"/users/email/verification" → "/api/users/email/verification"
"/users" → "/api/users"
"/swagger-ui/**" → "/api/swagger-ui/**"
"/v3/api-docs/**" → "/api/v3/api-docs/**"
```
- 토큰 없이 접근해야 하는 API들이 JWT 필터에 걸려 401 에러가 발생하던 문제 해결
- 회원가입 및 이메일 인증 요청 시 "유효한 토큰이 필요합니다" 에러 해결
- Swagger 문서 접근 시 인증 요구 문제 해결
- Context path 변경 시 필터와 Security 설정의 경로 패턴 일관성 유지 필요성
- 향후 새로운 인증 제외 경로 추가 시 `/api` prefix 고려 필요
> [FIX] JwtFilter에 경로에 /api를 붙여 필터에서 제외되도록 설정

- src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
- src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
Close #150 
- AccessChecker에 CustomUserDetilas를 기반으로 로그인 여부를 확인하는 로직을 삭제하였습니다
- Local환경에서 Context Path 설정 후 JWT 필터에서 경로 매칭이 실패하여 
인증이 필요 없는 경로에서도 토큰 검증이 실행되는 문제를 해결했습니다.
- **JWT Filter 경로 매칭 방식 변경**: `getRequestURI()` → `getServletPath()` 사용
- **AccessChecker 중복 로직 제거**: 인증된 사용자 검사를 `isAuthenticated()`로 책임 단일화
- **Configuration Properties 설정**: `@ConfigurationProperties`를 통한 경로 설정 관리
- **Security Config 경로 허용**: JWT Filter와 동일한 경로들을 `.permitAll()`로 설정
1. **Configuration Properties 주입 실패**
- `@Value`로 YAML List를 직접 주입할 수 없어 `@ConfigurationProperties` + `@Component` 방식으로 변경
2. **Properties 값이 빈 배열로 로드되는 문제**
- `@Component`와 `@EnableConfigurationProperties` 중복 사용으로 인한 충돌 해결
- `@Component` 방식으로 통일하여 Properties 클래스에서 직접 주입
3. **경로 매칭은 되지만 필터가 계속 실행되는 문제**
- JWT Filter는 정상적으로 건너뛰지만 Spring …
> [BE - FIX] 게시글 목록조회시 403에러 수정 및 로컬전용 Context-path추가

- src/main/java/com/kakaobase/snsapp/domain/members/controller/MemberController.java
- src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
- src/main/java/com/kakaobase/snsapp/global/common/email/dto/EmailRequest.java
Close #171 
- 사용자가 비밀번호를 변경할 수 있는 기능을 구현했습니다.
- 기존 비밀번호 검증과 새 비밀번호 설정을 위한 안전한 API를 제공합니다.
- **비밀번호 수정 API**: PUT /users/password 엔드포인트 구현
- **비밀번호 변경 DTO**: `MemberRequestDto`에 비밀번호 수정용 DTO 추가
- **비밀번호 검증 로직**:  DTO의 @Vaild기반 새 비밀번호 유효성 검사
- **비밀번호 수정 DTO 추가**: email과 새 비밀번호를 받는 요청 DTO
- **유효성 검증**: 비밀번호 형식 및 제약 조건 검증 어노테이션 적용
- **비밀번호 수정 엔드포인트**: 인증된 사용자의 비밀번호 변경 요청 처리
- **예외 처리**: 잘못된 요청에 대한 적절한 응답 처리
- **비밀번호 변경 비즈니스 로직**: 이메일 인증 후 새 비밀번호로 업데이트
- **암호화 처리**: 새 비밀번호를 안전하게 해시화하여 저장
- **트랜잭션 관리**: 비밀번호 변경 과정의 데이터 일관성 보장
이메일 인증시 요청으로 보내는 purpose필드값을 프론트와 통일할 필요가 있습니다
비밀번호 수정시: password-change
회원 탈퇴시: unregister
회원가입시: sign-up
> [BE - FEAT] 비밀번호 수정 기능 구현

- src/main/java/com/kakaobase/snsapp/domain/members/controller/MemberController.java
- src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
- src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
Close #173 
- 사용자 프로필 이미지 변경 기능 구현
- GitHub URL 수정 기능 구현
- 회원탈퇴 API의 중복된 인증 로직 제거
- **프로필 이미지 수정**
- 프로필 이미지 수정 DTO 구현
- MemberController에 프로필 이미지 수정 API 추가
- 프로필 이미지 수정 비즈니스 로직 구현
- **GitHub URL 수정**
- GitHub URL 수정 요청 DTO 추가
- Controller에 GitHub URL 수정 API 추가
- GitHub URL 수정 비즈니스 로직 구현
- 회원탈퇴 API에서 중복된 인증 로직(@PreAuthorize) 제거로 코드 최적화
- GitHub URL 유효성 검증 로직 확인 필요
- API 응답 형식 및 에러 처리 방식 통일성 검토
> [BE - FEAt] 사용자 프로필이미지, github링크 수정 구현

- .github/workflows/ci-dev.yml
- src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
- src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/converter/LikeConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentLikeService.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/domain/follow/controller/FollowController.java
- src/main/java/com/kakaobase/snsapp/domain/follow/converter/FollowConverter.java
- src/main/java/com/kakaobase/snsapp/domain/follow/dto/FollowResponse.java
- src/main/java/com/kakaobase/snsapp/domain/follow/entity/Follow.java
- src/main/java/com/kakaobase/snsapp/domain/follow/exception/FollowErrorCode.java
- src/main/java/com/kakaobase/snsapp/domain/follow/exception/FollowException.java
- src/main/java/com/kakaobase/snsapp/domain/follow/repository/FollowRepository.java
- src/main/java/com/kakaobase/snsapp/domain/follow/service/FollowService.java
- src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
- src/main/resources/application.yml
Close #178
- 팔로우/언팔로우 기능을 구현
- 팔로잉/팔로워 목록 조회 기능을 추가
- 게시글 및 댓글 조회 시 작성자와의 팔로우 상태를 함께 반환하도록 기능 추가
- **Follow Entity 및 도메인 로직 구현**
- Follow Entity 추가로 팔로우 관계 데이터 모델링
- 팔로우/언팔로우 요청 처리 비즈니스 로직 구현
- 자기 자신을 팔로우하지 못하도록 예외 처리 추가
- **Follow API 엔드포인트 추가**
- `POST /follow` - 팔로우 요청
- `DELETE /follow` - 언팔로우 요청  
- `GET /following` - 팔로잉 목록 조회
- `GET /followers` - 팔로워 목록 조회
- **응답 DTO 및 변환 로직**
- 팔로잉/팔로워 목록 조회용 응답 DTO 추가
- Follow 엔티티를 DTO로 변환하는 Converter 메서드 구현
- 재사용 가능한 User 정보 DTO 추가 및 책임 분리
- **팔로우 상태 통합**
- 게시글 상세/목록 조회 시 작성자와의 팔로우 여부 표시
- 댓글/대댓글 조회 시 팔로우 상태 정보 포함
- 특정 유저의 팔로잉 목록을 ID Set으로 반환하는 메서드 추가
- **데이터 일관성 개선**
- 프로필 이미지 필드명을 `image_url`로 통일 (기존 `profile_image`와 혼용 해결)
- 팔로우/언팔로우 시 사용자의 `followCount` 자동 조정
- **코드 품질 개선**
- 중복 주석 및 불필요한 코드 제거
- yml 파일의 중복 변수 정리
- 댓글/대댓글 좋아요 관련 미사용 DTO 제거
- …
> [BE - FEAT]follow도메인 구현 및 기존 로직에 반영

- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/BotRecommentService.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/domain/members/controller/MemberController.java
- src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
- src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
- src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostLikeService.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
- src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
Close #192 
- Post 엔티티의 객체 그래프 구조 개선 및 Service 계층 리팩토링
- 마이페이지에서 사용자의 활동 내역 조회 기능 구현 (작성 게시글, 작성 댓글, 좋아요한 게시글)
- 불필요한 DTO 및 메서드 정리를 통한 코드 최적화
- 댓글 삭제시 에러문제 해결
[[[REFACTOR] MemberId를 생성자로 받는것에서 Member객체 자체를 받도록 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/304c2ad)](https://github.com/100-hours-a-week/22-tenten-be/commit/304c2ad)
[[[REFACTOR] 변경된 Post에 맞게 Service로직 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/3baca1d)](https://github.com/100-hours-a-week/22-tenten-be/commit/3baca1d)
[[[REMOVE] 객체 정보수정로직은 Entity메서드 사용을 위해 관련 메서드, 사용되지 않는 메서드 삭제](https://github.com/100-hours-a-week/22-tenten-be/commit/de5d207)](https://github.com/100-hours-a-week/22-tenten-be/commit/de5d207)
[[[REMOVE] 객체 정보수정로직은 Entity메서드 사용하도록 …
> [BE - FEAT] 마이페이지 조회시 사용될 게시물 조회 기능 구현

- build.gradle
- src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
- src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
- src/main/resources/application.yml
Close #200 
- Spring Boot 애플리케이션에서 /actuator/health 엔드포인트를 활성화하여 헬스체크용 API 제공 필요
- 운영 환경 배포 시 LB(로드밸런서) 헬스체크를 위함
[[FEAT] Spring Boot Actuator 의존성 및 health endpoint 설정 추가](https://github.com/100-hours-a-week/22-tenten-be/commit/5072a6162111b13b4b85b9b302796c0fde5e9e70)
[[CHORE] /actuator/health 접근을 위한 SecurityConfig 및 JWT 필터 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/4f38bfd31f4e8b1e818fae25c45613b71c8fb571)
@1026hz
http://localhost:8080/actuator/health 테스트 완료
> [BE - FEAT] 헬스체크를 위한 Spring Boot Actuator 설정

- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/domain/members/controller/MemberController.java
- src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
Close #
- 특정 유저의 게시글 조회, 댓글 조회, 좋아요한 게시글 조회를 현재 유저가 아닌 path param을 통해 받도록 수정
[[FIX] 마이페이지 조회가 현재 유저Id가아닌 path param을 기반으로 조회하도록 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/2877a19e9f8448fc6865fc7aa962325b4139fcda)
[[FIX] 마이페이지 댓글조회, 좋아요 게시글 조회를 path param의 userId를 통해 조회하도록 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/662ae662ed21f07cde118b820fedf759a2b6d749)
[[STYLE] 좋아요 게시글 조회 매개변수를 적절하게 변경](https://github.com/100-hours-a-week/22-tenten-be/commit/bd28f2b4ae8e6fa6b91e9f15967780f620387cea)
[[FIX] 좋아요 게시글 조회 매개변수를 적절하게 변경, 유효성 검사 메서드 추가](https://github.com/100-hours-a-week/22-tenten-be/commit/241ca8bba6623f47b144ffa45f44daf00280fa40)
> [BE - FIX] 마이페이지 조회가 현재유저를 기반으로 조회되는 로직을 수정

- src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
- src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
Close #210
- 댓글 목록조회, 마이페이지 댓글조회, 댓글 상세조회 응답에 post_id필드 추가
[[FIX] 댓글 정보 반환Dto에 postId 추가](https://github.com/100-hours-a-week/22-tenten-be/commit/e3e1c33e5af4e098841c7c550f924edc203a7ff0)
[[REMOVE] 필요없는 메서드 제거](https://github.com/100-hours-a-week/22-tenten-be/commit/8a40c9bdea2d27e1f1e4d58afaaacddd396f1ad9)
[[REFACTOR] CommentInfo를 builder패턴으로 만들도록 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/50c1aae03ed0626508cc9cea7f51a1b23d4852e6)
> [BE - FIX] 댓글 조회 응답에 post_id필드 추가

- src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
- src/main/java/com/kakaobase/snsapp/domain/auth/converter/AuthConverter.java
- src/main/java/com/kakaobase/snsapp/domain/auth/dto/AuthResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/auth/exception/AuthException.java
- src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetails.java
- src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetailsService.java
- src/main/java/com/kakaobase/snsapp/domain/auth/service/AuthService.java
- src/main/java/com/kakaobase/snsapp/domain/auth/service/SecurityTokenManager.java
- src/main/java/com/kakaobase/snsapp/domain/auth/util/CookieUtil.java
- src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtUtil.java
- src/main/resources/application.yml
Close #127 
- Spring Boot 환경에서 JWT 기반 인증 시스템을 Cookie 방식으로 전면 개편
- AuthService의 아키텍처를 개선하여 코드 가독성과 유지보수성 향상
- AccessToken과 RefreshToken 모두 Cookie 기반으로 처리하도록 인증 로직 통합
- **AuthService 리팩토링**: SecurityContext 조작을 private 메서드로 캡슐화하여 코드 중복 제거
- **SecurityTokenManager 책임 분리**: 토큰 유효성 검사는 AuthService에서, 토큰 해싱 처리는 SecurityTokenManager에서 담당
- **메서드 간 결합도 감소**: 직접 매개변수 전달 방식으로 암묵적 의존성 제거
- **설정 추가**: yml에 AccessToken용 cookie name, path 설정 추가
- **CookieUtil 개선**: AccessToken과 RefreshToken 쿠키 생성 로직 통합 및 재사용성 향상
- **JWT 토큰 추출 방식 변경**: Header 기반에서 Cookie 기반으로 전환
- **CustomUserDetails 확장**: 로그인/토큰 재발급 시 필요한 name 필드 추가
- **응답 DTO 개선**: 로그인/AccessToken 재발급 시 사용되는 응답 DTO 네이밍 개선
- **로그인/토큰 재발급 API**: AccessToken을 쿠키로 주입하도록 로직 수정
- **예외 처리 개선**: AuthException이 상위 구현체를 받을 수 있도록 수정
- **불필요한 메서드 제거**: 중복되거나 사용되지 …
> [BE - REFACOTR] AccessToken을 Cookie로 발급하도록 수정

- src/main/java/com/kakaobase/snsapp/global/common/email/service/EmailSender.java
- src/main/java/com/kakaobase/snsapp/global/common/email/service/EmailVerificationService.java
- src/main/java/com/kakaobase/snsapp/global/config/RedisConfig.java
Close #216
- 기존 HashMap으로 저장하던 이메일 인증 로직을 Redis를 사용하도록 수정
[[REFACTOR] 인증메일을 Redis기반으로 하도록 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/364c768d0fb9b231939dd7730b17b9dad3b0e47c)
[[REMOVE] 필요없는 메서드 제거](https://github.com/100-hours-a-week/22-tenten-be/commit/5b99c5f9c05a59e68417f30bfc0c207073d51f09)
> [BE - REFACTOR]  이메일 인증 로직을 Redis를 사용하도록 변경

- src/main/java/com/kakaobase/snsapp/domain/follow/repository/FollowRepository.java
- src/main/java/com/kakaobase/snsapp/domain/follow/repository/custom/FollowCustomRepository.java
- src/main/java/com/kakaobase/snsapp/domain/follow/repository/custom/FollowCustomRepositoryImpl.java
- src/main/java/com/kakaobase/snsapp/domain/follow/scheduler/FollowCacheSyncScehduler.java
- src/main/java/com/kakaobase/snsapp/domain/follow/service/FollowCacheService.java
- src/main/java/com/kakaobase/snsapp/domain/follow/service/FollowCacheSyncService.java
- src/main/java/com/kakaobase/snsapp/domain/follow/service/FollowService.java
- src/main/java/com/kakaobase/snsapp/domain/follow/util/FollowCacheUtil.java
- src/main/java/com/kakaobase/snsapp/domain/members/converter/MemberConverter.java
- src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberResponseDto.java
- src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
- src/main/java/com/kakaobase/snsapp/domain/members/repository/MemberRepository.java
- src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
- src/main/java/com/kakaobase/snsapp/global/common/redis/CacheRecord.java
- src/main/java/com/kakaobase/snsapp/global/common/redis/error/CacheErrorCode.java
- src/test/java/com/kakaobase/snsapp/domain/members/repository/MemberRepositoryTest.java
Close #231
- 팔로워/팔로잉 수 조회 성능 최적화를 위한 Redis 캐싱 시스템 구현
- 회원 탈퇴 시 팔로우 관계 및 관련 카운트를 일괄 정리하는 기능 구현
- DB와 캐시 간 데이터 일관성 보장을 위한 동기화 스케줄러 구현
- **FollowCacheUtil**: Redis를 활용한 팔로워/팔로잉 수 캐싱 유틸리티 구현
- **FollowCacheService**: Look-aside 패턴으로 캐시 우선 조회 로직 구현
- **FollowCacheSyncService**: DB와 캐시 간 데이터 동기화 서비스 구현
- **스케줄러**: 주기적으로 캐시 데이터를 DB에 동기화하는 배치 작업 구현
- Member Entity 및 관련 DTO의 `followingCount`, `followerCount` 타입을 `Integer`에서 `Long`으로 변경
- 대규모 사용자 환경에서의 확장성 고려
- **FollowCustomRepository**에 회원 탈퇴 시 필요한 메서드들 구현:
- `deleteByFollowerUserId()`: 특정 회원이 팔로우한 모든 관계 삭제
- `deleteByFollowingUserId()`: 특정 회원을 팔로우하는 모든 관계 삭제
- `decrementFollowingCountForFollowersOf()`: 탈퇴 회원을 팔로우했던 사용자들의 팔로잉 수 감소
- `decrementFollowerCountForFollowingsOf()`: 탈퇴 회원이 팔로우했던 사용자들의 팔로워 수 감소
- `cleanupAllFollowRelationships()`: 위 4가지 …
> [BE - FEAT] 회원의 팔로우, 팔로잉 수에 캐싱 기능 추가 

- src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/Recomment.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/custom/CommentCustomRepositoryImpl.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/custom/RecommentCustomRepositoryImpl.java
- src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
- src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostLikeRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/custom/PostCustomRepository.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/custom/PostCustomRepositoryImpl.java
- src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
- src/main/java/com/kakaobase/snsapp/global/common/entity/BaseSoftDeletableEntity.java
<html>
<body>
<html><head></head><body><h1>PR 템플릿</h1>
<h2>📍 PR 타입 (하나 이상 선택)</h2>
<ul>
<li>[x] 기능 추가</li>
<li>[ ] 버그 수정</li>
<li>[ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트</li>
<li>[ ] 기타 사소한 수정</li>
</ul>
<h2>❗️ 관련 이슈 링크</h2>
<p>Close #</p>
<h2>📌 개요</h2>
<p>게시글 삭제 시 연관된 모든 데이터(댓글, 대댓글, 좋아요, 이미지)를 안전하게 삭제하는 기능을 구현했습니다. 복잡한 연관관계와 SoftDelete/HardDelete 혼재 상황을 고려하여 QueryDSL을 활용한 벌크 연산으로 성능과 안정성을 보장하도록 구현하였습니다.</p>
<h2>🔁 변경 사항</h2>
<h3>게시글 삭제 기능 구현</h3>
<ul>
<li><strong>PostDeleteService</strong>: 게시글 삭제 비즈니스 로직 구현</li>
<li><strong>PostCustomRepository</strong>: QueryDSL 기반 벌크 삭제 연산 구현</li>
<li><strong>삭제 순서</strong>: FK 제약조건을 고려한 안전한 삭제 순서 적용
<pre><code>RecommentLike → Recomment → CommentLike → Comment → PostLike → PostImage → Post
</code></pre></li>
</ul>
<h3>기술적 구현 사항</h3>
<ul> …
> [BE - FIX] 게시글, 댓글 삭제시 500에러 문제 발생 해결

- src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
- src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
- src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
- src/main/java/com/kakaobase/snsapp/global/common/redis/service/cacheService/AbstractCacheService.java
Close #234 
- CacheService의 필드 감소로직의 -부호가 이중처리되어 값이 증가하는 로직 수정
[[FIX] CommentRepo로 delete시 Recomment와의 관계가 CascadeType.ALL로 설정되있어서 FK…에러가 나는 버그 수정
](https://github.com/100-hours-a-week/22-tenten-be/commit/862bd35c15f97f54411e1ad3bd3ad254e4a8829d) 
[[REMOVE] 댓글 삭제시 작성자가 일치하는지 유효성 검사 중복 로직 제거(Controller와 중복됨)](https://github.com/100-hours-a-week/22-tenten-be/commit/64e2e94090afa78b2fef03431efe2cbb3534f734)
[[REFACTOR] 댓글 삭제시 불필요한 매개변수 memberId를 제거](https://github.com/100-hours-a-week/22-tenten-be/commit/8ee924d25e61805a80c4e630f2f57f0e4b86f78e)
[[FIX] CacheService의 필드 감소로직의 -부호가 이중처리되어 값이 증가하는 로직 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/1430369764b53a9a39710b3c13f7554796d79d27)
> [BE - FIX] 캐싱 필드 감소로직이 필드를 증가시키는 에러 수정

- src/main/java/com/kakaobase/snsapp/domain/comments/repository/custom/CommentCustomRepositoryImpl.java
- src/main/java/com/kakaobase/snsapp/domain/comments/repository/custom/RecommentCustomRepositoryImpl.java
Close #250 
-  댓글, 대댓글 목록 조회시 순차순 정렬 조건에 lt가 되어있던 로직 수정
> [BE - FIX] 댓글, 대댓글 목록 조회시 lt조건으로 조회하던 로직을 수정

- src/main/java/com/kakaobase/snsapp/global/config/WebSocketConfig.java
Close #234
- WebSocket 엔드포인트를 올바르게 `/api/ws`로 설정
- SockJS의 자동 `/info` 요청 처리를 위한 경로 수정
- **WebSocketConfig**: 엔드포인트를 `/api/ws/info`에서 `/api/ws`로 수정
- SockJS가 자동으로 `/api/ws/info` 경로에 사전 정보 요청을 보낼 수 있도록 설정
- SockJS 연결 과정에서의 자동 경로 처리 방식
> [BE - FIX] WebSocket 엔드포인트 설정 수정

- src/main/java/com/kakaobase/snsapp/domain/notification/listener/WebSocketSubscriptionListener.java
- src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationCommandService.java
Close #234
- WebSocket 알림 구독 경로를 상수화하여 코드 일관성 및 유지보수성 향상
- 하드코딩된 경로를 제거하고 중앙집중식 관리
- **NotificationCommandService**: `NOTIFY_SUBSCRIBE_PATH` 상수 추가
- **WebSocketSubscriptionListener**: 구독 경로를 `/user/queue/notification`으로 통일
- 모든 알림 전송 경로를 상수로 일관되게 관리
- WebSocket 경로 관리 전략 및 네이밍 컨벤션
> [BE - REFACTOR] WebSocket 알림 구독 경로 상수화

- src/main/java/com/kakaobase/snsapp/global/common/entity/WebSocketPacket.java
- src/main/java/com/kakaobase/snsapp/global/common/entity/WebSocketPacketImpl.java
Close #262 
- WebSocket 패킷 역직렬화 시 발생하는 InstantiationException 오류 수정
- Jackson이 abstract 클래스를 직접 인스턴스화하려던 문제 해결
- 알림 읽기/삭제 기능의 정상 동작 보장
- `@JsonTypeInfo`: Jackson이 다형성 처리 시 기본 구현체 지정
- `@JsonSubTypes`: 가능한 하위 타입과 식별자 매핑
- `defaultImpl = WebSocketPacketImpl.class`로 기본 구현체 설정
- `@JsonCreator`: Jackson이 객체 생성 시 사용할 생성자 지정
- `@JsonProperty`: JSON 필드와 생성자 파라미터 명시적 매핑
- 불변 객체의 안전한 역직렬화 보장
- 알림 읽기 패킷: `{"event":"notification.read","data":{"id":115}}`
- 알림 삭제 패킷: `{"event":"notification.delete","data":{"id":115}}`
- 이제 정상적으로 `WebSocketPacketImpl<NotificationRequestData>` 객체로 변환
- 모든 WebSocket 패킷 처리가 안정화됩니다
- 향후 다른 WebSocket 기능 추가 시에도 동일한 패턴 적용 가능
> [BE - FIX] WebSocket 패킷 역직렬화 오류 수정

- src/main/java/com/kakaobase/snsapp/domain/chat/controller/ChatController.java
- src/main/java/com/kakaobase/snsapp/domain/chat/service/ai/AiServerSseManager.java
- src/main/java/com/kakaobase/snsapp/domain/chat/service/communication/ChatWebSocketService.java
- src/main/java/com/kakaobase/snsapp/domain/chat/service/streaming/StreamingSessionManager.java
- src/main/resources/application-dev.yml
Close #261
- 실시간 AI 채팅봇 시스템의 안정성 및 디버깅 기능 강화
- WebSocket 메시지 처리 문제 해결 및 로깅 시스템 개선
- 스트리밍 중지 요청을 streamId 기반으로 변경하여 다중 스트림 지원
- AI 서버 통신 방식을 동기화하여 성능 최적화
- **ChatController**와 **ChatWebSocketService**의 큐 destination을 `/queue/chatbot`으로 통일
- WebSocket 응답 메시지가 클라이언트에 정상 전달되도록 수정
- 불필요한 의존성 제거 및 코드 정리
- `com.kakaobase.snsapp.domain.chat: DEBUG` - Chat 도메인 전체 로깅 활성화
- `org.springframework.messaging: DEBUG` - STOMP 메시지 처리 로깅
- `org.springframework.web.socket: DEBUG` - WebSocket 연결 상태 로깅
- `org.springframework.messaging.simp: DEBUG` - SimpMessagingTemplate 로깅
- **WebSocket 메시지 처리 과정 디버깅 가능**
- **ChatTimerManager**: 타이머 플로우 및 활성 타이머 수 추적
- **ChatBufferManager**: LoadingEvent 발행 단계별 상세 로깅
- **ChatEventListener**: 비동기 이벤트 처리 타이밍 및 스레드 정보 추적
- **ChatWebSocketService**: WebSocket 패킷 전송 성공/실패 상태 로깅
- …
> [BE - FEAT] 실시간 AI 채팅봇 시스템 개선 및 디버깅 강화

- src/main/java/com/kakaobase/snsapp/global/common/entity/WebSocketPacket.java
Close #295
- WebSocket 채팅 패킷(`chat.send`, `chat.typing`) 파싱 시 발생하는 `InstantiationException` 에러 해결
- Jackson 직렬화/역직렬화 과정에서 abstract class 인스턴스화 문제 수정
- `@JsonTypeInfo` 어노테이션 복원
- `As.EXISTING_PROPERTY` 사용으로 기존 `event` 필드를 타입 식별자로 활용
- `visible=true` 설정으로 JSON 출력에서 event 필드 유지
- `defaultImpl = WebSocketPacketImpl.class` 설정으로 안전한 fallback 제공
- chat.send 패킷 파싱 실패 해결
- chat.typing 패킷 파싱 실패 해결
- WebSocket 메시지 역직렬화 시 InstantiationException 제거
> [BE - FIX] WebSocket 채팅 패킷 파싱 에러 해결

- src/main/java/com/kakaobase/snsapp/domain/chat/controller/ChatController.java
- src/main/java/com/kakaobase/snsapp/global/config/WebSocketConfig.java
Close #295
- WebSocket 채팅 패킷 파싱 실패 문제 해결
- ChatController 경로별 분리를 통한 타입 안전성 확보
- Principal 타입 체크 오류 수정
- JSON 역직렬화 과정에서 발생하는 ClassCastException 해결
- `@JsonTypeInfo` 어노테이션 복원으로 Jackson 역직렬화 문제 해결
- `As.EXISTING_PROPERTY` 사용하여 기존 `event` 필드를 타입 식별자로 활용
- 별도 `type` 필드 없이 하위 호환성 유지
- WebSocket에서 `Principal`이 `UsernamePasswordAuthenticationToken` 타입임을 고려
- `token.getPrincipal()` 방식으로 올바른 `CustomUserDetails` 추출
- 공통 `extractUserId()` 유틸 메서드 구현
- 통합 `/chat` 엔드포인트를 이벤트별 경로로 분리:
- `/chat.send` → `WebSocketPacket<ChatData>`
- `/chat.typing` → `WebSocketPacket<SimpTimeData>`  
- `/chat.stop` → `WebSocketPacket<StreamStopData>`
- `/chat.stream.end.ack/nack` → `WebSocketPacket<StreamAckData>`
- `WebSocketPacket<?>` 와일드카드를 구체적 타입으로 변경
- switch문 기반 이벤트 분기 로직 제거
- 수동 캐스팅 및 Map 추출 로직 완전 제거
- `chat.typing` …
> [BE - FIX] WebSocket 채팅 패킷 파싱 및 타입 안전성 개선

- src/main/java/com/kakaobase/snsapp/domain/chat/service/streaming/StreamingSessionManager.java
Close #295
- 스트림 완료 시 @Async 메서드 반환 타입 문제로 인한 DB 저장 실패 해결
- 프론트엔드에서 chat.stream.error 발생 원인 수정
- `ChatCommandService.saveBotMessage()` 메서드가 `@Async` 어노테이션 사용하면서 `Long` 타입 반환
- Spring `@Async` 규칙: 오직 `void` 또는 `Future<T>` 타입만 반환 가능
- 에러 메시지: "Invalid return type for async method (only Future and void supported): class java.lang.Long"
```java
// 변경 전
Long botChatId = chatCommandService.saveBotMessage(session.getUserId(), finalResponse);
// 변경 후
Long botChatId = chatCommandService.saveBotMessageSync(session.getUserId(), finalResponse);
```
- 스트림 완료 시 즉시 chat_id 반환 가능
- DB 저장 성공 후 정상적인 `chat.stream.end` 이벤트 전송
- 프론트엔드 에러 해결: `chat.stream.error` → `chat.stream.end`
- 기존 `@Async` 메서드는 유지하여 다른 곳에서 사용 중인 코드 영향 최소화
- 이미 존재하는 `saveBotMessageSync()` 동기 메서드 활용
- 스트림 완료 처리는 즉시 chat_id가 필요하므로 동기 처리가 적합 …
> [BE - FIX] 스트림 완료 시 비동기 메서드 호출 문제 수정

- src/main/resources/application-local.yml
Close
- WebSocket 연결시 발생하는 만료된 JWT 토큰 에러 로그 도배 문제 해결
- 보안 관련 DEBUG 로그와 Tomcat ERROR 로그 레벨 조정으로 로그 가독성 개선
- `application-local.yml`에서 보안 관련 패키지 로그 레벨 조정:
- `com.kakaobase.snsapp.global.security`: DEBUG → WARN
- `org.springframework.security`: DEBUG → WARN  
- `org.apache.juli.logging.DirectJDKLog`: OFF로 설정
- WebSocket 에러 로그 도배 방지를 위한 주석 추가
- 이는 좋아요 게시글 에러 로그를 확인하기 위한 임시조치로, 차후 WebSocket QA때 근본적인 해결 필요
> [BE - FIX] WebSocket연결 에러 로그 도배 문제 임시 처리

- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
WebSocket JWT 토큰 만료 에러 로그 도배 문제 임시 해결
- WebSocket 연결시 발생하는 만료된 JWT 토큰 에러 로그 도배 문제 임시 해결
- 
- `application-local.yml`, `application-dev.yml`에서 로그 레벨 조정:
- `com.kakaobase.snsapp.global.security`: DEBUG → WARN
- `org.springframework.security`: DEBUG → WARN  
- `org.apache.juli`: OFF로 설정 (DirectJDKLog 포함)
- `org.apache.catalina`: WARN으로 설정
- `org.apache.tomcat`: WARN으로 설정
- 이는 좋아요 게시물 조회의 에러로그를 보기 위한 임시 조치로, 이후 근본적인 원인인 WebSoket연결 문제를 해결할때 수정해야함
> [BE - FIX] WebSocket 에러 로그 도배 방지를 위한 로그 레벨 조정

- src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
- src/main/java/com/kakaobase/snsapp/domain/posts/repository/custom/PostCustomRepositoryImpl.java
Close #281
- 좋아요한 게시글 조회시 `Duplicate key 53` 에러 해결
- WebSocket 연결시 발생하는 만료된 JWT 토큰 에러 로그 도배 문제 해결
- PostCustomRepositoryImpl의 LEFT JOIN 조건 수정으로 중복 데이터 반환 방지
- **PostCustomRepositoryImpl.java**: `findLikedPostsWithCursor`에서 LEFT JOIN 조건 수정
- **문제**: `likedByMemberId = currentMemberId`일 때 `currentUserLike.post.eq(post)` 조건이 항상 적용되어 해당 게시글의 모든 좋아요와 JOIN
- **해결**: 조건 자체를 `null`로 설정하여 JOIN 완전 비활성화
- **PostConverter.java**: 불필요한 빈 줄 제거
- **application-local.yml**, **application-dev.yml**에서 로그 레벨 조정:
- `com.kakaobase.snsapp.global.security`: DEBUG → WARN
- `org.springframework.security`: DEBUG → WARN  
- `org.apache.juli`: OFF로 설정 (DirectJDKLog 포함)
- `org.apache.catalina`: WARN으로 설정
- `org.apache.tomcat`: WARN으로 설정
> [BE - FIX] 좋아요한 게시글 조회 에러 해결

- src/main/java/com/kakaobase/snsapp/domain/posts/repository/custom/PostCustomRepositoryImpl.java
Close #281
- 좋아요한 게시글 조회 API에서 발생하는 "Duplicate key 53" 오류와 QueryDSL NPE 오류 해결
- PostCustomRepositoryImpl의 findLikedPostsWithCursor 메서드에서 조건부 조인 로직 개선
- QueryDSL에서 중복 데이터 생성을 방지하기 위한 LEFT JOIN 조건 수정
- 조건부 조인된 테이블을 SELECT 절에서 안전하게 참조하도록 로직 개선
- NPE 방지를 위한 3단계 조건문 적용
- 좋아요한 게시글 조회시 currentMemberId와 likedByMemberId가 같을 때의 예외 처리 강화
- PostStatsCache의 중복 키 오류가 완전히 해결되었는지 모니터링 필요
- 대용량 데이터에서의 성능 테스트 고려
> [BE - FIX] 좋아요한 게시글 조회 오류 해결

- src/main/java/com/kakaobase/snsapp/domain/notification/controller/NotificationController.java
- src/main/java/com/kakaobase/snsapp/domain/notification/dto/response/NotificationCount.java
- src/main/java/com/kakaobase/snsapp/domain/notification/dto/response/NotificationFetchResponse.java
- src/main/java/com/kakaobase/snsapp/domain/notification/repository/NotificationRepository.java
- src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationCommandService.java
- src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationService.java
Close #332
- 사용자의 안읽은 알림 개수를 조회할 수 있는 새로운 API 엔드포인트를 추가했습니다.
- 기존 알림 목록 조회 API와 분리하여 성능을 개선하고 클라이언트가 필요에 따라 선택적으로 호출할 수 있도록 했습니다.
- `GET /api/users/notifications/counts`: 안읽은 알림 개수 조회
- `NotificationRepository.countByReceiverIdAndIsRead()`: 사용자별 읽음 상태에 따른 알림 개수 조회 메서드 추가
- `NotificationCommandService.getUnreadNotificationCount()`: 안읽은 알림 개수 조회 서비스 로직 구현
- `NotificationService.getNotifCount()`: 봇 사용자 예외 처리 포함한 알림 개수 반환 로직
- `NotificationCount`: 알림 개수 전용 응답 DTO 추가
- `NotificationFetchResponse`: 기존 unreadCount 필드 제거하여 책임 분리
- Repository 반환 타입을 `long`에서 `Long`으로 변경하여 타입 일관성 개선
- Null 안전성 체크 추가
- 기존에는 알림 목록 조회 시 매번 개수를 계산했지만, 이제 별도 API로 분리하여 필요시에만 호출 가능
- Spring Data JPA의 Query Method를 활용하여 효율적인 COUNT 쿼리 실행
- 향후 읽은/안읽은 알림 구분 조회, 알림 타입별 개수 조회 등으로 확장 가능
- Redis 캐싱 적용으로 성능 개선 여지 있음
> [BE - FEAT] 사용자 안읽은 알림 개수 조회 API 추가
