100-hours-a-week/22-tenten-be

src/main/java/com/kakaobase/snsapp/domain/members/service/EmailVerificationService.java, src/main/java/com/kakaobase/snsapp/global/common/email/EmailSender.java, src/main/java/com/kakaobase/snsapp/global/config/EmailConfig.java, src/main/resources/templates/verification-email.html
Close #6 [BE - FEAT] Member 도메인 구현
- 
- MemberEntity구현
- MemberRepository구현
- MemberConverter구현
- MemberRequestDto 구현
- MemberResponseDto구현
- MemberErrorCode 구현
- MemberException구현
- MemberController구현
- MemberService구현
- EmailSender구현
- EmailController구현
- yml파일에 DB, Email관한 환경변수 추가
- 이메일 인증 html템블릿 구현
회원 정보 변경 로직은 V2마이페이지 구현때 추가 예정
=> [FEAT] 이메일인증, 회원가입 기능 구현

src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
Close #50
- Cors 설정에 local:3001추가
Cors의 에 set AllowOrigins에 개발용 로컬 프론트엔드 포트 local:3001추가
=> [CHORE] Cors 설정에 local:3001추가

src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
=> [CHORE] Cors 설정에 kakaobase도메인추가, 개발용 프론트엔드 ip추가

src/main/resources/application.yml
Close #56
- 쿠키를 http에도 주입받을 수 있도록 수정
=> [Chore] cookieSecure를 false로 변환

src/main/java/com/kakaobase/snsapp/domain/posts/dto/BotRequestDto.java, src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
=> [BE - FIX] 소셜봇 작성 요청에 소셜봇 게시글 필터링

src/main/java/com/kakaobase/snsapp/global/config/SwaggerConfig.java, src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java, src/main/resources/application.yml
Close #115 
- Nginx 리버스 프록시 환경에서 Swagger UI가 정상적으로 표시되지 않는 문제 수정
SwaggerConfig Base URL 변경
a7e0f018694e7ad644b15240b3f4b1737cbf2108
SecurityConfig Preflight 요청 허용
75e3b184cd08000632f4c352bee3fa4ef070cbd0
Swagger 관련 프로퍼티 삭제
15858d403d043e60f718b194ef2d9e1b4c4d83d7
=> [BE - !HOTFIX] Nginx 리버스 프록시 환경에서 Swagger UI가 정상적으로 표시되지 않는 문제 수정

src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
Close #147
- Cors에 링크 추가
CorsConfig에 
https://localhost:3000,
https://localhost:3001 추가
=> [CHORE] CORS에 https localhost추가

src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
Close #163
- 회원가입 요청 시 `class_name` 필드를 찾지 못해 발생하는 400 에러를 수정했습니다.
- `MemberRequestDto.java`에 누락된 `@JsonProperty` 어노테이션을 추가하여 JSON 직렬화/역직렬화 문제를 해결했습니다.
- `MemberRequestDto.java` 파일의 `class_name` 필드에 `@JsonProperty("class_name")` 어노테이션 추가
- Git 병합 과정에서 누락된 main 브랜치의 수정사항을 develop 브랜치에 재적용
- 이번 이슈는 Git 병합 과정에서 발생한 문제로, main 브랜치에서 추가된 
`@JsonProperty` 어노테이션이 develop 브랜치 병합 시 무시되면서 발생했습니다.
- cherry-pick 시도 시 empty commit이 발생한 것은 Git이 해당 내용이 이미 존재한다고 판단했기 때문으로 추정됩니다.
=> [BE - FIX] MemberReqest에@JsonProperty추가

.github/workflows/ci-dev.yml
=> [CI/CD] ci-dev.yml

src/main/java/com/kakaobase/snsapp/domain/test/test.java
=> [CI/CD] ci-dev-test

src/main/resources/application-prod.yml
Close #
- prod환경의 Cookie관련 환경변수 Same-Site를 None으로 변경
[[CHORE] prod환경의 Cookie Same-Site설정을 None으로 변경](https://github.com/100-hours-a-week/22-tenten-be/commit/a674260a055a2748553828b60092fb075e86851a)
=> [CHORE] prod환경의 Cookie Same-Site설정을 None으로 변경

src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
Close #246 
- 기존 LocalDateTime형식이였던 TimeStamp포맷을 UTC Instant기준으로 수정
"created_at": "2025-06-27T00:35:17"
"created_at": "2025-06-27T00:43:04.000000Z"
=> [FIX] BotPostService가 양식에 맞게 createAt을 출력하도록 수정

src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
Close #248 
- JWT필터의 swagger api 허용 목록 수정
[[FIX] JWT필터의 swagger api 허용 목록 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/b93d8e6e8ec6fcac229be856fba18e6ec600630e)
실제 배포환경과 로컬 환경의 swagger허용 api가 다를 가능성 존재. 배포환경에서 확인 필요
=> [BE - FIX] JWT필터의 swagger api 허용 목록 수정

src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentLikeService.java, src/main/java/com/kakaobase/snsapp/domain/notification/controller/NotificationController.java, src/main/java/com/kakaobase/snsapp/domain/notification/converter/NotificationConverter.java, src/main/java/com/kakaobase/snsapp/domain/notification/dto/records/NotificationAckData.java, src/main/java/com/kakaobase/snsapp/domain/notification/dto/records/NotificationFetchData.java, src/main/java/com/kakaobase/snsapp/domain/notification/error/NotificationErrorCode.java, src/main/java/com/kakaobase/snsapp/domain/notification/error/NotificationException.java, src/main/java/com/kakaobase/snsapp/domain/notification/repository/NotificationRepository.java, src/main/java/com/kakaobase/snsapp/domain/notification/repository/custom/CustomNotificationRepositoryImpl.java, src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationCommandService.java, src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationService.java, src/main/java/com/kakaobase/snsapp/domain/notification/util/FilterResult.java
Close #234
- 알림 시스템의 에러 처리 구조를 개선하고 알림 조회 응답에 읽지 않은 알림 개수를 포함하도록 기능을 추가했습니다.
- WebSocket 기반 실시간 알림 시스템의 안정성과 사용자 경험을 향상시켰습니다.
- `NotificationErrorCode` 도입으로 알림 전용 에러 코드 체계 구축
- `NotificationException` 리팩토링으로 도메인별 예외 처리 개선
- `NotificationAckData` 구조 개선 및 Builder 패턴 적용
- WebSocket 에러 패킷 처리 방식 통일
- `NotificationFetchData` 도입으로 알림 목록과 읽지 않은 개수 동시 제공
- `filterNotifications` 메서드 개선으로 각 알림의 읽음 상태 확인 및 카운팅
- `sendNotificationFetchData` 메서드 추가로 개선된 데이터 구조 WebSocket 전송
- 무효한 알림 자동 필터링 및 비동기 삭제 처리
- 컨버터 메서드명 정리 및 일관성 확보
- 불필요한 import 정리 및 코드 구조 개선
- 로깅 메시지 개선으로 디버깅 편의성 향상
- 알림 시스템의 성능 최적화를 위한 추가 캐싱 전략 검토 필요
- 실시간 알림 전송 실패 시 재시도 로직 추가 고려
- 알림 개수가 많은 경우 페이징 처리 필요성 검토
=> [BE - FIX] YouTubeSummaryService 컴파일 에러 수정

src/main/java/com/kakaobase/snsapp/domain/notification/error/NotificationErrorCode.java, src/main/java/com/kakaobase/snsapp/domain/notification/repository/custom/CustomNotificationRepositoryImpl.java, src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationCommandService.java
Close #262
- 실시간 WebSocket 기반 알림 시스템을 구현하고 안정성을 개선했습니다.
- 알림 조회 시 읽지 않은 개수를 포함한 개선된 응답 구조를 제공합니다.
- 알림 배치 조회 시 발생하던 중복 키 에러를 해결했습니다.
- `NotificationErrorCode` 도입으로 알림 전용 에러 코드 체계 구축
- `NOTIFICATION_FETCH_FAIL`: 알림 데이터 조회 실패
- `NOTIFICATION_DELETE_FAIL`: 알림 데이터 삭제 실패
- `NOTIFICATION_NOT_FOUND`: 알림을 찾을 수 없음 (`resource_not_found`)
- `NOTIFICATION_READ_FAIL`: 알림 읽기 실패 (`notification.read.nack`)
- `NotificationException` 리팩토링으로 도메인별 예외 처리 개선
- `NotificationAckData` 구조 개선 및 Builder 패턴 적용
- WebSocket 에러 패킷 처리 방식 통일
- `NotificationFetchData` 도입으로 알림 목록과 읽지 않은 개수 동시 제공
```java
public record NotificationFetchData(
int unread_count,                    // 읽지 않은 알림 개수
List<WebSocketPacket<?>> notifications // 알림 목록
) {}
```
- `filterNotifications` 메서드 개선으로 각 알림의 읽음 상태 확인 및 카운팅
- …
=> [BE - FIX] 알림 목록 조회시 발생 에러 수정

src/main/java/com/kakaobase/snsapp/domain/notification/repository/NotificationRepository.java, src/main/java/com/kakaobase/snsapp/domain/notification/repository/custom/CustomNotificationRepositoryImpl.java, src/main/java/com/kakaobase/snsapp/domain/notification/service/NotificationCommandService.java, src/main/resources/application-dev.yml
=> [BE - FIX] 알림 조회 시 NPE발생 문제 해결

src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
Close #275
- JWT 필터에서 회원가입 API 경로 패턴 수정
- API 경로 일관성 맞춤 (`/users` → `/api/users`)
- 회원가입 API 경로 패턴을 `/users`에서 `/api/users`로 수정
- 다른 API 경로들과 일관성 유지
- 모든 API 경로가 `/api` prefix를 사용하도록 통일되었습니다
=> [BE - FIX] 회원가입 API 경로 수정

src/main/java/com/kakaobase/snsapp/domain/chat/service/ai/AiServerHttpClient.java, src/main/java/com/kakaobase/snsapp/domain/comments/service/BotRecommentService.java, src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java, src/main/java/com/kakaobase/snsapp/domain/posts/service/async/YouTubeSummaryService.java
Close #
- WebClient빈 중복 등록 에러 해결
=> [BE - FIX] WebClient중복 빈 등록 에러 해결

src/main/java/com/kakaobase/snsapp/domain/chat/controller/ChatController.java, src/main/java/com/kakaobase/snsapp/domain/chat/exception/errorcode/ChatErrorCode.java, src/main/java/com/kakaobase/snsapp/domain/chat/service/streaming/ChatBufferManager.java
Close #261
- WebSocket 메시지 처리 문제 해결 및 에러 응답 시스템 완성
- **ExceptionHandler 모호성 해결**: `@MessageExceptionHandler` 중복 문제 수정으로 WebSocket 메시지 처리 정상화
- **에러 상황별 사용자 알림**: AI 서버 연결 실패, 버퍼 관련 에러 시 적절한 에러 패킷 전송
- **새로운 에러 코드 추가**: `CHAT_BUFFER_NOT_FOUND`, `CHAT_BUFFER_INVALID`
- **사용자 무한 대기 방지**: 모든 에러 상황에서 명확한 피드백 제공
- **에러 처리 시스템 완성**: 모든 실패 케이스에서 사용자에게 명확한 피드백 제공
- **WebSocket 안정성 대폭 향상**: ExceptionHandler 모호성 해결로 메시지 처리 정상화
- **성능 최적화**: 동기 방식 채택으로 불필요한 컨텍스트 스위칭 제거
- **다중 스트림 지원**: streamId 기반 처리로 사용자당 여러 스트림 동시 관리 가능
=> [BE - FEAT] 실시간 AI 채팅봇 에러 응답로직 구현

src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
Close #290 
- 소셜봇 대댓글 이어서 작성하도록 로직 수정
[[FIX] 대댓글이 새로 작성됐을 경우에도 소셜봇이 이어서 대댓글 작성하도록](https://github.com/100-hours-a-week/22-tenten-be/commit/bee59b3cbe92aefe7cc28d8ba92479746edc7a81)
[[FIX] 프록시 기반 코드 정리](https://github.com/100-hours-a-week/22-tenten-be/pull/291/commits/b7a496fb49751a5f538fabf9bae44696f9f128a1)
=> [BE - FIX] 소셜봇 대댓글 이어서 작성하도록 로직 수정

src/main/java/com/kakaobase/snsapp/domain/chat/model/StreamingSession.java, src/main/java/com/kakaobase/snsapp/domain/chat/service/ai/AiServerSseManager.java, src/main/java/com/kakaobase/snsapp/domain/chat/service/streaming/StreamingSessionManager.java
Close #295
- SSE 패킷 파싱 오류 및 연결 안정성 문제 해결
- 타임아웃 기반 세션 관리 및 조건부 헬스체크 구현
- LinkedHashMap과 String 타입 모두 처리 가능한 적응형 파싱 구현
- 연결 확인 메시지와 실제 스트림 데이터 구분 처리
- AI 서버 데이터 형식 불일치 문제 해결 (content → message 필드)
- 서버 다운 에러(502, 503, 504, ConnectException)와 일시적 에러 구분
- DISCONNECTED 상태에서만 헬스체크 수행하여 불필요한 요청 제거
- 즉시 재시도 로직 제거, 30초 주기 통합 관리로 변경
- 마지막 SSE 응답으로부터 30초 타임아웃 감지
- 타임아웃된 세션 자동 정리 및 사용자 알림
- AI_SERVER_TIMEOUT 에러를 통한 사용자 피드백
- SSE 스트림용 무한 타임아웃 설정
- ReadTimeoutHandler 제거로 연결 안정성 향상
- 불필요한 헬스체크 제거로 네트워크 리소스 절약
- 조건부 실행으로 AI 서버 부하 감소
- 서버 다운과 일시적 에러 구분으로 적절한 대응
- 타임아웃 기반 세션 정리로 메모리 누수 방지
=> [BE - FIX] SSE 패킷 파싱 및 연결 관리 개선

src/main/java/com/kakaobase/snsapp/domain/chat/repository/custom/ChatMessageCustomRepositoryImpl.java, src/main/java/com/kakaobase/snsapp/domain/chat/service/ai/AiServerSseManager.java, src/main/java/com/kakaobase/snsapp/global/config/WebClientConfig.java, src/main/resources/application.yml
=> [BE - FIX] 하드코딩된 timeout 수정 및 채팅 조회 수정

src/main/resources/application-dev.yml
Close #318
- dev 서버 디스코드 웹훅 추가
[[CHORE] application-dev.yml에 discord 추가](https://github.com/100-hours-a-week/22-tenten-be/commit/47e93d262b670d074a8ed42ffaaf402ff7ef6c73)
=> [BE - CHORE] dev 서버 디스코드 웹훅 추가

src/main/resources/application-dev.yml
Close #318
- application-dev.yml 들여쓰기 수정
[[CHORE] application-dev.yml 들여쓰기 수정](https://github.com/100-hours-a-week/22-tenten-be/commit/0be3fb8e2658b61715688e19fbfe35784eb4d569)
=> [CHORE] application-dev.yml 들여쓰기 수정

deploy/appspec.yml, deploy/scripts/health_check.sh
Close #321
- CodeDeploy 단계 중 AfterAllowTraffic 에서 헬스체크 진행한 이후 정상 트래픽이 들어오는지 확인하기 위해 스크립트 추가
[[FEAT] 블루그린 배포 시 헬스체크 스크립트 추가](https://github.com/100-hours-a-week/22-tenten-be/commit/7357110c795739c90cf6409380de58816e62e7c0)
=> [FEAT] CodeDeploy health check 스크립트 추가
